### ISSUE TITLE
future plans

### ISSUE THREAD

**Issue by janmarek** [EvanHahn/expecting.js#6]
Hi, what are your future plans with this library? What ideas do you have?

**Comment by EvanHahn** [comment]
I'm very open to suggestions. Here are some initial thoughts:
- add `.to.deepEqual` and move `.to.eql` into more obscurity. (Not exactly sure what this entails, but it's something I've been thinking of.)
- easier extensibility. I love the `sinon-chai` project and would love to allow similar extensions.
- removal of `expect().fail()` unless I can understand its usefulness.
- add tests across a suite of browsers using an automation tool like Sauce Labs or Browserstack 

I'd like to see a few people using `0.4.0` before I jump into making too many changes; if nobody switches to this library, I'd rather not waste my time.

**Comment by janmarek** [comment]
I use my [own fork](https://github.com/janmarek/expect2/commits/master) of this library.

What I think this library needs is:
- very easy extensibility (so you can avoid many feature requests for adding some obscure assertions)
- improve the quality of the code and tests (one source file and one test file? seriously?)

But to be honest right now I am considering switching to should.js which has nice docs and seems to be well maintained.

**Comment by EvanHahn** [comment]
What about something like this?

``` js
expect.extend({
  name: 'tiny',
  check: function (actual) {
    return actual < 1
  },
  errorMessage: function (actual) {
    return 'expected ' + actual + ' to be less than 1'
  },
  negatedErrorMessage: function (actual) {
    return 'expected ' + actual + ' to be greater than 1'
  }
})

expect(5).to.be.tiny()
```

**Comment by janmarek** [comment]
I am not much in favor of creating special APIs. Maybe a few little changes would be enough:
- expose Assertion.prototype
- rename this.obj
- this.assert should return this
- this.assert should also accept strings as error messages
- document the API which is now internal and keep it stable

``` javascript
expect.assertions.tiny = function (threshold = 1) {
    return this.assert(
        this.value < threshold,
        `expected ${i(this.value)} to be less than 1`,
        `expected ${i(this.value)} to be greater than 1`
    );
};
```

This is not that terrible, right?

Or we can pass the "this" as an function parameter somehow:

``` javascript
expect.addAssertion('tiny', function (expect, threshold = 1) {
    expect.assert(
        expect.value < threshold,
        `expected ${i(this.value)} to be less than 1`,
        `expected ${i(this.value)} to be greater than 1`
    );
});
```

We can go many ways...

**Comment by EvanHahn** [comment]
I think there are a lot of good things to talk about here, not just the extensibility API. I've opened up a few issues:
- extensibility: #8 
- renaming `this.obj`: #9 
- `this.assert` should return `this`: #10 
- refactoring the internals: #11 
- `this.assert` should accept strings: #12 

Feel free to submit pull requests and we'll figure things out!

I'm closing this issue for now—let's move discussion to the finer-grained issues.
